packages:
  - "apps/*"
  - "packages/*"

catalog:
  react: "^19"
  react-dom: "^19"
  next: "^15"
  typescript: "^5"
  "@types/node": "^20"
  "@types/react": "^19"
  "@types/react-dom": "^19"
  postcss: "^8"
  tailwindcss: "^3"
  autoprefixer: "^10"
  eslint: "^9"
  eslint-config-next: "^15"
  "@eslint/eslintrc": "^3"
  "@eslint/js": "^9"
  "@swc/cli": "^0.6.0"
  "@swc/core": "^1"
  prettier: "^3"
  lucide-react: "^0.303.0"
